### ISSUE TITLE
Translated Page Versions Not Updated

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#194] opened 2019-02-07 18:28 UTC
**Describe the bug**
When a language other than English is selected using the translation options provided in top right selector former wording is displayed. Example "Process Details" pages is still showing as the former "Process Timeline".
![screen shot 2019-02-07 at 1 24 16 pm](https://user-images.githubusercontent.com/2421382/52434017-66f4c600-2adc-11e9-8e04-2f71ac2cc6b9.png)

**Expected behavior**
When and changes are made to the English text other languages should also be updated.  

**Additional context**
We may need to establish a process for systematic regular updates to other languages.  If we are relaying on professional translation regular updates at releases should be established.

**Comment by mzagaja** [comment] 2019-02-07 18:46
Did you fix this for Process timeline? Your test case does not reproduce for me.

**Comment by theryankelly** [comment] 2019-02-07 19:31
I have not implemented any fix.  I can reproduce in Firefox and Chrome.  Choosing "Portuguese" the content, title included, reverts back to "Process Timeline" (Linha do tempo do processo) rather than "Process Details".

**Comment by mzagaja** [comment] 2019-02-07 20:18
Oh I see, so the screenshot is actually of an English translation of the Portuguese translation? If so, that makes sense why I was confused.

Anyways this is currently working as designed. Because we do not wish to delete professional translations that may be added in the future we have told the automated translation tool to only trigger if the foreign translations are blank. The burden is on the user to go in and blank out the foreign translations to trigger a fresh translation after an update to the English page. The side effect of implementing a change to update it automatically is that users would blow away professional translations with machine translations if they change the English text.

I think we can consider adding a boolean here to let the user decide the behavior. Otherwise if we end up not doing professional translations it might be worth just backing this feature out since it doesn't provide anything better than Chrome's auto-translate or a translation widget (like Bing offers) provides.

**Comment by theryankelly** [comment] 2019-03-06 22:02
Need to bring this issue to Integrated Communications to discuss manual vs automated translation efforts.

**Comment by mzagaja** [comment] 2020-01-30 20:26
Closing this since manual translations are now off the table.

**Closed by mzagaja** 2020-01-30 20:26 UTC
Labels: content edit
