### ISSUE TITLE
Find Out - Sort Tagged Items

### ISSUE THREAD

**Issue by smithWEBtek** [MAPC/digitalhub#354] opened 2019-07-26 15:09 UTC
**Describe the feature. What should a user be able to do?**
The sort order of items should be newest at the top. Sort will be addressed in this issue: #354 Events is a special case where the Join us for an event prompt should always be first when "events" is selected. This events prompt should match the style of the home page event box.

Add sort functionality to taggings controller.** Once implemented on Announcement, the respective date fields for Announcement, Event and Report will be used in a sorting method for organizing the order of items to display on the Find Out filter page. This issue is dependent upon completion of issue #351 Add Published Date to Announcement 

**Why do we need this feature?**
for sorting tagged items in the Find Out filter page.

**Alternatives**
Refinery has a 'position' field native to the app, which could serve 1 of the purposes of sorting items, but would not address the need for a date to be associated with an Announcement.

**Additional context**
The other data models ( Event and Report ) currently have date fields which can be used for sorting. 

Summary of expected display of cards based on filter selections:
 
<img width="760" alt="summary" src="https://user-images.githubusercontent.com/16054332/62877640-7eb03f80-bcf5-11e9-8c9a-de44d66a004e.png">

**Comment by theryankelly** [comment] 2020-01-22 17:38
Re-opening this issue.  When publications were added to the Hub. Sort is not behaving as intended.  All content should be order by date (newest at top) regardless of type.

**Comment by mzagaja** [comment] 2020-01-30 20:23
Resolved in https://github.com/MAPC/digitalhub/pull/465

**Closed by mzagaja** 2020-01-30 20:23 UTC
